### ISSUE TITLE
Variable parsing in advanced loop commands doesn't work

### ISSUE THREAD

**Issue by dschreij** [smathot/osweb#18]
See https://forum.cogsci.nl/discussion/comment/19394#Comment_19394 for an example.
A command such as `slice` only accepts values (e.g. `slice 3 6`) and doesn't work with variables (e.g. `slice [start] [end]`). This is probably also the case for other loop operations that accept parameters.

**Comment by smathot** [comment]
I happened to run into that too, actually. Yes, thanks for picking that up.
