### ISSUE TITLE
The loop table should be generated during the Run phase

### ISSUE THREAD

**Issue by smathot** [smathot/osweb#2]
Right now, the `loop` table is initialized in part in `from_string()`  and in part in `prepare()`. However, this is inconsistent with the behavior of OpenSesame where the `loop` table is initialized during `run()` in the `_create_live_datamatrix()` function.

For reference, see:

- https://github.com/smathot/OpenSesame/blob/loewenfeld/libopensesame/loop.py#L177

**Comment by dschreij** [comment]
This is fixed now, isn't it?

**Comment by smathot** [comment]
Yes!
