### ISSUE TITLE
Variables are no longer correctly parsed in loop items

### ISSUE THREAD

**Issue by dschreij** [smathot/osweb#3]
I don't really remember but I think this used to work....

If you place a variable in a loop cell (e.g. `[var1]`) this expression is not parsed and the value of this  cell or variable will just be `[var1]` in the sequence that follows and also logged as such.

**Comment by dschreij** [comment]
Even though you unassigned me from this one, I think this is closely related to #2 so I am going to see if I can fix both in one go.

Unrelated: is it possible to transfer all issues from shyras/osweb too, or should we recreate them here?

**Comment by smathot** [comment]
> Unrelated: is it possible to transfer all issues from shyras/osweb too, or should we recreate them here?

I'm not aware of an automated way to do that, unfortunately.
