### ISSUE TITLE
Using 'always' as a break-if statement in a loop causes TypeError

### ISSUE THREAD

**Issue by smathot** [smathot/osweb#31]
If you enter 'always' as a break-if statement in a loop, the following error occrus:

![image](https://user-images.githubusercontent.com/594936/90484457-7f648880-e136-11ea-9129-91ff1b7823b3.png)

**Comment by smathot** [comment]
@dschreij I just gave this a shot, but it's trickier than it seems. Basically, the break-if statement is almost completely broken, beyond just choking on 'always'.

**Comment by dschreij** [comment]
Likely this is because of the complicated structure of osweb with all its function chaining. Did the latest commit fix it (as it is listed after you previous comment?)

**Comment by smathot** [comment]
Yes, this should be fixed with that commit and closed if you approve the PR!
