### ISSUE TITLE
css and js map files in the OSWeb 1.3.9 needs updating

### ISSUE THREAD

**Issue by eort** [smathot/osweb#47]
Not sure in how far an issue this is, but apparently some files in the 1.3.9 release are still called 1.3.8
See this discussion in the forum:

https://forum.cogsci.nl/discussion/6658/osweb-1-3-9-js-map-files#latest

**Comment by smathot** [comment]
Thanks, I'll make sure to check this when bundling the next version. (Fyi, things related to packaging are best posted in the open-cogsci/opensesame-extension-osweb repository.)
