### ISSUE TITLE
Allow/make translation of the splash screen

### ISSUE THREAD

**Issue by mirh** [smathot/osweb#63]
This part specifically
https://github.com/open-cogsci/osweb/blob/64106d0736d340907bb460e642738ac4b48b0463/src/js/osweb/system/screen.js#L268-L272
(yes, I know I can just manually edit the thing myself then, but my supervisor is a legit boomer)

**Comment by smathot** [comment]
Thanks for your input. We already have an issue open for this though (#25 ), so I'm closing this one.
