### ISSUE TITLE
CSV files not embedded in file pool with OSWeb 2.0 backend

### ISSUE THREAD

**Issue by acochard** [smathot/osweb#99]
Although [it was supported in OSWeb 1.4](https://forum.cogsci.nl/discussion/7376/try-osweb-1-4-with-new-features-for-online-experiments), CSV files can no longer be used as source file for loop tables in OSWeb 2.0. Inspecting the browser console (in Chrome & Firefox) shows that no file is embedded in the file pool despite having a CSV file in the file bank on OpenSesame. Other types of files such as png, mp3, txt, etc., are well detected.

**Comment by smathot** [comment]
Thanks for reporting this!

**Comment by smathot** [comment]
I can't replicate this issue. I attached a test experiment that uses a csv source for a loop item. This runs fine with OSWeb 2.0.1. Can you explain in more detail what doesn't work for you?

[CSVtest.zip](https://github.com/open-cogsci/osweb/files/12607903/CSVtest.zip)

**Comment by acochard** [comment]
That's strange, I keep getting this error from the browser console: `Loop item refers to non-existing source file: loop.csv`. The csv is in the file bank in OpenSesame, but the file pool is empty in the browser. You can try CSVtest on this [JATOS link](https://jatos-server.web.rug.nl/publix/34/start?batchId=36&generalMultiple), does it work for you? _(jzip attached below)_

I reported this issue on the forum [here](https://forum.cogsci.nl/discussion/comment/28356) and someone did too [here](https://forum.cogsci.nl/discussion/8746/reading-independent-variables-from-file-osweb-opensesame-4-0).

For information: I am using OpenSesame 4.0.5 and OSWeb 2.0.1. My browser are Chrome 116 and Firefox 117.

[CSVtest_forJATOS.zip](https://github.com/open-cogsci/osweb/files/12608823/CSVtest_forJATOS.zip)

![Capture d’écran 2023-09-14 144516](https://github.com/open-cogsci/osweb/assets/120182246/7c209ede-e396-46f5-b14d-a9dc1e576742)

**Comment by smathot** [comment]
Ah, thanks! The issue appears to be that Windows tags `.csv` files as Excel files, and this avoids OpenSesame from recognizing them and including them in the pool.
